// Generated by CoffeeScript 1.10.0
var app, express, expressHandlebars, server, soundcloud;

console.log("Initializing.");

express = require('express');

expressHandlebars = require('express-handlebars');

soundcloud = require('./lib/soundcloud');

app = express();

app.engine('handlebars', expressHandlebars({
  defaultLayout: 'main'
}));

app.set('view engine', 'handlebars');

app.use(express["static"]('static'));

app.get("/", function(req, res) {
  return res.render('home', {
    title: "TESTAN"
  });
});

server = app.listen(9001, function() {
  var host, port;
  host = server.address().address;
  port = server.address().port;
  return console.log("Listening at " + host + ":" + port);
});
