// Generated by CoffeeScript 1.10.0
var app, config, express, expressHandlebars, fs, server, soundcloud, url;

console.log("Initializing.");

express = require('express');

expressHandlebars = require('express-handlebars');

url = require('url');

fs = require('fs');

config = JSON.parse(fs.readFileSync("./config.json"));

soundcloud = require('./lib/soundcloud');

soundcloud.setApiKey(config.clientId);

app = express();

app.engine('handlebars', expressHandlebars({
  defaultLayout: 'main'
}));

app.set('view engine', 'handlebars');

app.use(express["static"]('static'));

app.get("/", function(req, res) {
  var page;
  page = {};
  page.title = "SoundVane";
  return res.render('home', page);
});

app.get("/url/*", function(req, res) {
  var link, page, soundcloudUrl;
  link = url.parse(req.originalUrl);
  soundcloudUrl = link.pathname.substr(5);
  page = {};
  console.log("stopit");
  return soundcloud.getIdRecsList(soundcloudUrl).then(function(results) {
    console.log(results);
    page.tracks.ids = results;
    if (link.host !== "soundcloud.com") {
      page.title = "Whoops.";
    } else {
      page.title = "Recommendations";
    }
    console.log(page);
    return res.render('recommendations', page);
  });
});

app.get("/about", function(req, res) {
  var page;
  page = {};
  page.title = "About Us";
  return res.render('about', page);
});

server = app.listen(9001, function() {
  var host, port;
  host = server.address().address;
  return port = server.address().port;
});
